import { defineType, defineArrayMember } from "sanity";

export default defineType({
  name: "pageBuilder",
  title: "Page Builder",
  type: "array",
  of: [
    defineArrayMember({ type: "textBlock" }),
    defineArrayMember({ type: "featureGrid" }),
    defineArrayMember({ type: "statsCounter" }),
    defineArrayMember({ type: "logoBar" }),
    defineArrayMember({ type: "imageGallery" }),
    defineArrayMember({ type: "videoEmbed" }),
    defineArrayMember({ type: "testimonials" }),
    defineArrayMember({ type: "faq" }),
    defineArrayMember({ type: "contactForm" }),
    defineArrayMember({ type: "attorneyGrid" }),
    defineArrayMember({ type: "practiceAreaGrid" }),
    defineArrayMember({ type: "anchoringAttorneyBand" }),
    defineArrayMember({ type: "contactMethods" }),
    defineArrayMember({ type: "ctaBand" }),
    defineArrayMember({ type: "envisageHero" }),
    defineArrayMember({ type: "richTextSection" }),
    defineArrayMember({ type: "textImageSplit" }),
    defineArrayMember({ type: "highlightGrid" }),
    defineArrayMember({ type: "insightsGrid" }),
    defineArrayMember({ type: "recognitionBand" }),
    defineArrayMember({ type: "locationGrid" }),
    defineArrayMember({ type: "imageBand" }),
  ],
});
